server:
  port: 8081
  
spring:
  application:
    name: simple-auction-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.auctionaggregator: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"